name: Nix

on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v16
      # TODO: add a binary cache
      # - uses: cachix/cachix-action@v10
      #   with:
      #     name: YOURCACHE
      #     authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix flake check --accept-flake-config
        # Pre-build the system configuration
      - run: nix build --accept-flake-config .
  check-formatting:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v16
      - run: nix shell nixpkgs#alejandra -c alejandra -c .

